name: "Windows Binary Builder"

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install loguru aiohttp asyncio pyinstaller requests
      - name: Build executable
        run: |
          pyinstaller --icon=keygen.ico --onefile .\keygen.py --name HamsterKeygen-v${{ github.run_number }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: dist/HamsterKeygen-v${{ github.run_number }}.exe


  create-release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Windows build
        uses: actions/download-artifact@v2
        with:
          name: windows-build
          path: ./dist
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./dist/*
          tag: v${{ github.run_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}